-- Esquema PostgreSQL para Supabase.
-- Ejecutar en Supabase > SQL Editor. No incluye credenciales.

CREATE TABLE IF NOT EXISTS categorias (
  id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  descripcion varchar(200),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS clientes (
  id_cliente integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  telefono varchar(20),
  correo varchar(100),
  direccion varchar(200),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS proveedores (
  id_proveedor integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(150) NOT NULL,
  telefono varchar(20),
  correo varchar(100),
  direccion varchar(200),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS productos (
  id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(50) NOT NULL UNIQUE,
  id_categoria integer NOT NULL REFERENCES categorias(id_categoria),
  id_proveedor integer NOT NULL REFERENCES proveedores(id_proveedor),
  nombre varchar(150) NOT NULL,
  marca varchar(100),
  precio_compra numeric(10,2) NOT NULL,
  precio_venta numeric(10,2) NOT NULL,
  stock_actual integer NOT NULL DEFAULT 0,
  stock_minimo integer NOT NULL DEFAULT 0,
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO')),
  imagen text
);

CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  usuario varchar(50) NOT NULL UNIQUE,
  "contraseña" varchar(255) NOT NULL,
  rol varchar(20) NOT NULL DEFAULT 'VENDEDOR' CHECK (rol IN ('ADMIN', 'VENDEDOR')),
  estado varchar(10) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE IF NOT EXISTS ventas (
  id_venta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_venta varchar(20) NOT NULL UNIQUE,
  id_cliente integer NOT NULL REFERENCES clientes(id_cliente),
  id_usuario integer NOT NULL REFERENCES usuarios(id_usuario),
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metodo_pago varchar(10) NOT NULL CHECK (metodo_pago IN ('EFECTIVO', 'QR', 'TARJETA')),
  descuento numeric(10,2) NOT NULL DEFAULT 0,
  monto_recibido numeric(10,2) NOT NULL DEFAULT 0,
  cambio numeric(10,2) NOT NULL DEFAULT 0,
  total numeric(10,2) NOT NULL,
  estado varchar(12) NOT NULL DEFAULT 'COMPLETADA' CHECK (estado IN ('COMPLETADA', 'ANULADA'))
);

CREATE TABLE IF NOT EXISTS detalle_ventas (
  id_detalle_venta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta integer NOT NULL REFERENCES ventas(id_venta) ON DELETE CASCADE,
  id_producto integer NOT NULL REFERENCES productos(id_producto),
  cantidad integer NOT NULL,
  precio_unitario numeric(10,2) NOT NULL,
  subtotal numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movimientos (
  id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto integer NOT NULL REFERENCES productos(id_producto),
  tipo_movimiento varchar(10) NOT NULL CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'ALERTA')),
  cantidad integer NOT NULL,
  precio_compra numeric(10,2),
  id_proveedor integer REFERENCES proveedores(id_proveedor),
  motivo varchar(150) NOT NULL,
  observacion varchar(250),
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  stock_anterior integer NOT NULL DEFAULT 0,
  stock_nuevo integer NOT NULL DEFAULT 0
);

INSERT INTO categorias (id_categoria, nombre, descripcion, estado)
VALUES (1, 'Aceites', 'Aceites y lubricantes para vehículos', 'ACTIVO')
ON CONFLICT (id_categoria) DO NOTHING;

INSERT INTO proveedores (id_proveedor, nombre, telefono, correo, direccion, estado)
VALUES (1, 'Proveedor Automotriz S.A.', '70000000', 'proveedor@gmail.com', 'La Paz - Bolivia', 'ACTIVO')
ON CONFLICT (id_proveedor) DO NOTHING;

INSERT INTO clientes (id_cliente, nombre, telefono, estado)
VALUES (1, 'Juan Perez', '70000000', 'ACTIVO')
ON CONFLICT (id_cliente) DO NOTHING;

INSERT INTO usuarios (id_usuario, nombre, usuario, "contraseña", rol, estado)
VALUES (1, 'Administrador', 'admin', '123456', 'ADMIN', 'ACTIVO')
ON CONFLICT (id_usuario) DO NOTHING;

INSERT INTO productos (id_producto, codigo, id_categoria, id_proveedor, nombre, marca, precio_compra, precio_venta, stock_actual, stock_minimo, estado)
VALUES (1, '7841234567890', 1, 1, 'Aceite 15W-40 1L', 'Shell', 30.00, 45.00, 26, 5, 'ACTIVO')
ON CONFLICT (id_producto) DO NOTHING;

INSERT INTO ventas (id_venta, numero_venta, id_cliente, id_usuario, fecha, metodo_pago, total, estado)
VALUES (1, 'V-000001', 1, 1, '2026-08-17 10:25:38', 'QR', 90.00, 'COMPLETADA')
ON CONFLICT (id_venta) DO NOTHING;

INSERT INTO detalle_ventas (id_detalle_venta, id_venta, id_producto, cantidad, precio_unitario, subtotal)
VALUES (1, 1, 1, 2, 45.00, 90.00)
ON CONFLICT (id_detalle_venta) DO NOTHING;

INSERT INTO stock_movimientos (id_movimiento, id_producto, tipo_movimiento, cantidad, motivo, observacion, fecha, stock_anterior, stock_nuevo)
VALUES
 (1, 1, 'ENTRADA', 10, 'Ingreso de mercadería', 'Entrada de 10 unidades de aceite', '2026-08-17 10:21:44', 18, 28),
 (2, 1, 'SALIDA', 2, 'Venta V-000001', 'Salida por venta', '2026-08-17 10:33:28', 28, 26)
ON CONFLICT (id_movimiento) DO NOTHING;

SELECT setval(pg_get_serial_sequence('categorias', 'id_categoria'), COALESCE((SELECT MAX(id_categoria) FROM categorias), 1));
SELECT setval(pg_get_serial_sequence('clientes', 'id_cliente'), COALESCE((SELECT MAX(id_cliente) FROM clientes), 1));
SELECT setval(pg_get_serial_sequence('proveedores', 'id_proveedor'), COALESCE((SELECT MAX(id_proveedor) FROM proveedores), 1));
SELECT setval(pg_get_serial_sequence('productos', 'id_producto'), COALESCE((SELECT MAX(id_producto) FROM productos), 1));
SELECT setval(pg_get_serial_sequence('usuarios', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM usuarios), 1));
SELECT setval(pg_get_serial_sequence('ventas', 'id_venta'), COALESCE((SELECT MAX(id_venta) FROM ventas), 1));
SELECT setval(pg_get_serial_sequence('detalle_ventas', 'id_detalle_venta'), COALESCE((SELECT MAX(id_detalle_venta) FROM detalle_ventas), 1));
SELECT setval(pg_get_serial_sequence('stock_movimientos', 'id_movimiento'), COALESCE((SELECT MAX(id_movimiento) FROM stock_movimientos), 1));